### ISSUE TITLE
Question About Use of BlobToolKit

### ISSUE THREAD

**Issue by foreignsand** [ccgproject/ccgp_assembly#1]
In the flowchart depicting the pipeline used by CCGP for genome assembly, there is a line connecting the 'Contamination Screening: BlobToolKit' box to the 'ARIMA Mapping Pipeline' box. This suggests that HiC reads are mapped to contigs produced by HiFiasm *after* they have been decontaminated using BlobToolKit. Is this correct?

I find the BlobToolKit docs to be a bit opaque and am hoping I can avoid puzzling out the pipeline for a little while longer.

Cheers,
Emily

**Comment by merlyescalona** [comment]
Hi, yes, that's correct. I'll update the Blobtools section as soon as I can describing how I have it working. It is the simplest configuration I could set up.  

In any case, I'd recommend to check this: https://pipelines.tol.sanger.ac.uk/blobtoolkit .

**Comment by foreignsand** [comment]
Great! I've looked at the blobtoolkit pipeline and it's a bit esoteric. Any guidelines you can provide would be much appreciated.

Thanks so much!

Cheers,
Emily
