### ISSUE TITLE
Add License for re-use

### ISSUE THREAD

**Issue by tbrown91** [ccgproject/ccgp_assembly#2]
Hi Merly,

We have received a suggestion to add this resource to the [ERGA Knowledge Hub](https://knowledge.erga-biodiversity.eu/). We think it would be a great fit to our library of biodiversity genomics resources, but we require a re-usage license for all of the resources. Would you consider adding one to this repository?

Many thanks and all the best,

Tom

**Comment by merlyescalona** [comment]
Hi Tom, thanks, I'll check on that and get back to you. M.
